package com.lutfi.mymiawapp.model

import com.lutfi.mymiawapp.R

data class Cat(
    val id: Int,
    val image: Int,
    val name: String,
    val description: String,
    val detail: String,
)

val dummyCats = listOf(
    Cat(1, R.drawable.persia, "Persia", "Kucing Persia memiliki bulu yang panjang dan lebat dengan wajah yang bulat dan hidung pesek.","Kucing Persia adalah salah satu ras kucing yang paling terkenal dan ikonik di dunia. Mereka memiliki bulu yang panjang, lebat, dan sangat halus yang dapat bervariasi dalam berbagai warna dan pola. Ciri khasnya adalah wajah yang bulat dengan mata besar yang cenderung cokelat atau biru. Hidung mereka pesek, dan telinganya kecil. Secara keseluruhan, penampilan Persia adalah yang elegan dan anggun.\\nSifatnya tenang, santai, dan cenderung memiliki kepribadian yang ramah. Mereka suka duduk-duduk di sekitar rumah dan menyukai perhatian dari pemiliknya. Persia adalah kucing yang kurang aktif secara fisik dan lebih suka berdiam diri atau bermain dengan mainan di dalam rumah."),
    Cat(2, R.drawable.siamese, "Siamese", "Siamese dikenal dengan tubuh yang ramping, mata biru tajam, dan bulu pendek yang halus.","Kucing Siamese adalah ras kucing yang sangat elegan dan cerdas. Mereka memiliki tubuh yang ramping dengan bulu yang pendek, halus, dan berkilau. Yang paling mencolok adalah mata mereka yang besar dan berwarna biru tajam, serta telinga yang besar dan segitiga. Pola bulu mereka sering kali menunjukkan warna cerah pada wajah, telinga, ekor, dan kaki.\\nSifatnya sangat bersemangat dan vokal. Siamese adalah kucing yang berani, aktif, dan seringkali terikat erat dengan pemiliknya. Mereka suka berbicara dengan suara khas mereka untuk berkomunikasi dan mendapatkan perhatian."),
    Cat(3, R.drawable.maine_coon, "Maine Coon", "Maine Coon adalah kucing terbesar di antara semua ras dan memiliki bulu dan ekor yang lebat.","Maine Coon adalah salah satu ras kucing terbesar di dunia. Mereka memiliki tubuh yang besar dan kuat dengan bulu yang panjang, tebal, dan lebat. Ekor mereka panjang dan berbulu tebal, dan telinga mereka berbentuk segitiga dengan ujung yang lebih lebar. Tidak hanya itu, tetapi Maine Coon juga memiliki tampilan yang elegan dan ekspresif.\\nSifatnya sangat ramah, bersahabat, dan tenang. Mereka suka bermain dan seringkali mempertahankan sifat main-main mereka bahkan saat dewasa. Maine Coon adalah kucing yang baik untuk keluarga karena mereka cenderung dekat dengan semua anggota keluarga."),
    Cat(4, R.drawable.bengal, "Bengal", "Kucing Bengal memiliki bulu yang mirip dengan harimau, dengan corak berbintik atau berstrip.","Kucing Bengal adalah salah satu ras yang memiliki penampilan paling eksotis. Bulu mereka mirip dengan motif harimau dengan corak berbintik atau berstrip yang kontras. Tubuh mereka ramping dan otot, memberi mereka penampilan yang kuat dan dinamis. Mata mereka cenderung besar dan berwarna hijau atau kuning.\\nSifatnya sangat aktif, energetik, dan penuh semangat. Mereka suka bermain dan bisa menjadi kucing yang cerdas jika dirangsang secara mental. Kucing Bengal adalah pilihan yang baik untuk pemilik yang aktif yang ingin bermain bersama kucing mereka."),
    Cat(5, R.drawable.ragdoll, "Ragdoll", "Ragdoll memiliki tubuh besar, bulu yang lembut, dan mata biru besar.", "Kucing Ragdoll mendapatkan namanya dari sifatnya yang santai ketika diangkat, seperti \"boneka yang lembek.\" Mereka memiliki bulu yang panjang, halus, dan mata biru besar yang mencolok. Telinga mereka sedang, dan tubuh mereka besar dengan kaki yang panjang.\\nSifatnya sangat santai, lembut, dan mudah diurus. Mereka suka berada di dekat pemiliknya dan seringkali akan merelaksasikan tubuh mereka ketika digendong seperti boneka yang lembek. Ragdoll adalah kucing yang cocok untuk keluarga yang menghargai kucing yang bersahabat dan santai."),
    Cat(6, R.drawable.scottish_fold, "Scottish Fold", "Scottish Fold memiliki telinga yang melipat ke bawah, memberikan tampilan yang unik.","Ciri khas Scottish Fold adalah telinga mereka yang melipat ke bawah, memberikan mereka tampilan yang unik dan menggemaskan. Mereka memiliki wajah manis dengan mata besar dan tubuh yang proporsional. Bulu mereka bisa pendek atau sedang, tergantung pada varietasnya.\\nSifatnya umumnya manis, ramah, dan suka berinteraksi dengan manusia. Scottish Fold adalah kucing yang cocok untuk pemilik yang menginginkan kucing yang memiliki ciri khas fisik yang unik dan sifat yang menyenangkan."),
    Cat(7, R.drawable.sphynx, "Sphynx", "Sphynx adalah kucing tanpa bulu yang terkenal dan memiliki kulit yang lembut dan tampilan yang unik.","Sphynx adalah salah satu ras kucing yang paling tidak biasa karena mereka hampir tidak memiliki bulu sama sekali. Kulit mereka halus, dan tubuh mereka terasa hangat saat disentuh. Mereka memiliki kepala yang agak besar dengan telinga besar yang berbentuk segitiga.\\nSifatnya sangat aktif, penuh energi, dan suka bermain. Mereka juga sangat sosial dan membutuhkan banyak perhatian dari pemiliknya. Sphynx adalah kucing yang unik dan menarik untuk pemilik yang mencari pengalaman yang berbeda dalam memelihara kucing."),
    Cat(8, R.drawable.balinese, "Balinese", "Balinese memiliki bulu yang panjang dan halus, dengan tubuh yang anggun.","Balinese adalah varietas kucing yang memiliki bulu panjang dan halus, namun memiliki struktur tubuh yang mirip dengan Siamese. Bulu mereka panjang terutama di ekor, telinga, dan kaki. Wajah mereka anggun dengan mata yang cerah dan telinga yang besar.\\nSifatnya aktif, sosial, dan cerdas. Mereka suka bermain dan berinteraksi dengan manusia, menjadikan mereka teman yang baik untuk pemilik yang suka bermain bersama kucing."),
    Cat(9, R.drawable.british_shorthair, "British Shorthair", "British Shorthair memiliki tubuh yang tegap dan bulu yang tebal.","British Shorthair adalah kucing dengan bulu pendek yang tebal dan lebat. Tubuh mereka tegap dan berotot, dengan kepala yang besar dan telinga yang kecil. Wajah mereka cenderung bulat, dan mata mereka besar dan ekspresif.\\nSifatnya tenang, baik, dan mudah diurus. Mereka adalah kucing yang santai dan cenderung tidak terlalu aktif. British Shorthair adalah pilihan yang baik untuk pemilik yang menghargai kucing yang tenang dan bersahabat."),
    Cat(10, R.drawable.abyssinian, "Abyssinian",  "Abyssinian adalah salah satu ras tertua yang dikenal dan memiliki bulu yang pendek dan motif berbintik-bintik.","Kucing Abyssinian adalah salah satu ras tertua yang dikenal dan memiliki bulu pendek dengan motif berbintik-bintik yang mencolok. Tubuh mereka ramping dan otot, dengan mata yang besar dan telinga yang sedang.\\nSifatnya sangat aktif, cerdas, dan penuh semangat. Mereka suka bermain dan seringkali memerlukan stimulasi mental untuk tetap bahagia. Abyssinian adalah kucing yang cocok untuk pemilik yang ingin kucing yang aktif dan cerdas."),
)